# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "nightly-2024-09-06"
components = [ "rust-src", "llvm-tools", "rust-analyzer" ]
profile = "minimal"
target = "avr-specs/avr-attiny1616.json"
